require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
