version: '3.8'

volumes:
  pgdata:

services:
  app:
    tty: true
    build: .
    stdin_open: true
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - RAILS_DB_NAME=greenatom
      - RAILS_DB_USER=greenatom
      - RAILS_DB_PASS=greenatom123
      - RAILS_DB_HOST=db

  db:
    image: postgres:15
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-greenatom}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-greenatom123}
      POSTGRES_DB: ${DB_DATABASE:-greenatom}
